!define BORDER_COLOR #3078b8
!define ARROW_COLOR #3078b8
!define BACKGROUND_COLOR #efefef
!define BORDER_WIDTH 1
!define FONT_NAME "PingFang SC, Helvetica, Tahoma, Arial, Hiragino Sans GB, Heiti SC, Microsoft YaHei, WenQuanYi Micro Hei"

skinparam Shadowing false
skinparam roundCorner 10
skinparam ArrowColor ARROW_COLOR
skinparam FontName FONT_NAME
skinparam backgroundColor #FFF

skinparam class {
  BorderColor BORDER_COLOR
  BackgroundColor BACKGROUND_COLOR
  AttributeFontSize 12
  FontSize 14
  BorderThickness BORDER_WIDTH
  FontName FONT_NAME
}

skinparam activity {
  BackgroundColor BACKGROUND_COLOR  
  BorderColor BORDER_COLOR
  BarColor #3078b8
  DiamondBorderColor BORDER_COLOR
  DiamondBackgroundColor BACKGROUND_COLOR
  BorderThickness BORDER_WIDTH
  FontSize 12
  StartColor BORDER_COLOR
  EndColor BORDER_COLOR
  FontName FONT_NAME
}

skinparam node {
  BackgroundColor BACKGROUND_COLOR  
  BorderColor BORDER_COLOR
  FontName FONT_NAME
}

skinparam rectangle {
  BorderColor BORDER_COLOR
  FontName FONT_NAME
  BackgroundColor BACKGROUND_COLOR
  BorderThickness BORDER_WIDTH
}

skinparam component {
  BackgroundColor BACKGROUND_COLOR  
  BorderColor BORDER_COLOR
  FontName FONT_NAME
  BorderThickness BORDER_WIDTH
}

skinparam database {
  BackgroundColor BACKGROUND_COLOR  
  BorderColor BORDER_COLOR
  BorderThickness BORDER_WIDTH
  FontName FONT_NAME
}

skinparam sequence {
  Participant {
    BackgroundColor BACKGROUND_COLOR 
    BorderColor BORDER_COLOR
    BorderThickness BORDER_WIDTH
    FontName FONT_NAME
  }
  Box {
    BorderColor BORDER_COLOR
    FontName FONT_NAME
  }
  LifeLine {
    BorderColor BORDER_COLOR
    FontName FONT_NAME
  }
  Group {
    BorderColor BORDER_COLOR
    BorderThickness BORDER_WIDTH
    FontName FONT_NAME
  }
}

skinparam collections {
  BackgroundColor BACKGROUND_COLOR  
  BorderColor BORDER_COLOR
  FontName FONT_NAME
}

skinparam state {
  BackgroundColor BACKGROUND_COLOR
  BorderThickness BORDER_WIDTH
  BorderColor BORDER_COLOR
  FontSize 12
  AttributeFontSize 10
  StartColor BORDER_COLOR
  EndColor BORDER_COLOR
  FontName FONT_NAME
}

skinparam archimate {
  BorderColor BORDER_COLOR
  FontName FONT_NAME
}

skinparam object {
  BorderColor BORDER_COLOR
  BackgroundColor BACKGROUND_COLOR
  AttributeFontSize 12
  FontSize 14
  BorderThickness BORDER_WIDTH
  FontName FONT_NAME
}

skinparam actor {
  BackgroundColor BACKGROUND_COLOR
  BorderColor BORDER_COLOR
  BorderThickness BORDER_WIDTH
  FontName FONT_NAME

}
skinparam legend {
  FontSize 12
  BackgroundColor BACKGROUND_COLOR
  BorderThickness BORDER_WIDTH
  BorderColor BORDER_COLOR
  FontName FONT_NAME
}
skinparam partition {
  BorderColor BORDER_COLOR
  AttributeFontSize 12
  FontSize 14
  BorderThickness BORDER_WIDTH
  FontName FONT_NAME
}
